name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the Docker image"
        required: true
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate tag format
        run: |
          TAG=${{ github.event.release.tag_name || github.event.inputs.tag_name }}
          if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag $TAG does not match the format x.y.z (semantic versioning)"
            exit 1
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with dynamic tag
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ivangonzalezg/icetex-status-monitor:${{ github.event.release.tag_name || github.event.inputs.tag_name }}
            ivangonzalezg/icetex-status-monitor:latest
